backend:
  name: github
  repo: pemdesbontolebang/kelara
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "profil"
    label: "Profil Desa"
    files:
      - label: "Tentang Desa"
        name: "tentang"
        file: "tentang.html"
        fields:
          - { label: "Isi Halaman", name: "body", widget: "markdown" }
