backend:
  name: github
  repo: pemdesbontolebang/kelara  # GANTI jika repo Anda punya nama berbeda
  branch: main                    # Atau "master" jika itu nama branch Anda

media_folder: "static/img"        # Folder tempat gambar disimpan dalam repo
public_folder: "/img"             # Lokasi gambar di URL website

collections:
  - name: "profil"
    label: "Profil Desa"
    folder: "content/profil"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Isi", name: "body", widget: "markdown" }

  - name: "perangkat"
    label: "Perangkat Desa"
    folder: "content/perangkat"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nama", name: "nama", widget: "string" }
      - { label: "Jabatan", name: "jabatan", widget: "string" }
